[http.routers]
  [http.routers.Router-1]
    rule = "Host(`localhost`)"
    service = "my-service"

[http.services]
  [http.services.my-service.loadBalancer]
    [[http.services.my-service.loadBalancer.servers]]
      url = "http://127.0.0.1:8000/"
